Repository pyqa/prodigyqa, pull requests merged in 2019-02, with the labels that each got.

#38 Web Scraper for links Implementation
  .travis.yml
  Examples/FilesCompare/samplecomparisontest.py
  Examples/samplewebspidertest.py
  Tests/TestSeleniumKeywords.py
  imgqa/__init__.py
  imgqa/browseractions.py
  imgqa/comparison.py
  imgqa/readme_compare.md
  imgqa/setup_scrapper.tmpl
  imgqa/spider.py
  requirements.txt
  setup.py
Labels: enhancement, review

#39 TST: Test Case Addition + Scrapy Fixes as needed + Browser Actions(minor fix)
  .travis.yml
  Examples/sampleseleniumtest.py
  imgqa/browseractions.py
  imgqa/setup_scrapper.tmpl
  imgqa/spider.py
  requirements.txt
  setup.py
Labels: review

#42 Add a Gitter chat badge to README.md
  README.md
Labels: in progress

#44 fixed bug
  setup.py
Labels: review

#41 Python-Saucelab integration example
  Examples/samplesaucelabseleniumtest.py
Labels: review

#47 Spellchecker
  Examples/samplespellcheckker.py
  README.md
  imgqa/utils.py
  requirements.txt
  setup.py
Labels: review

#49 Email
  Examples/sampleemailtest.py
  README.md
  imgqa/email.py
Labels: review
